"""empty message

Revision ID: 2378d06011c5
Revises: 76ab53b66aa2
Create Date: 2019-11-10 01:08:42.192191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2378d06011c5'
down_revision = '76ab53b66aa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payroll', sa.Column('assigned_office_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'payroll', 'assigned_office', ['assigned_office_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payroll', type_='foreignkey')
    op.drop_column('payroll', 'assigned_office_id')
    # ### end Alembic commands ###
