"""empty message

Revision ID: 39430ae73fcf
Revises: bcad9f8f3ddb
Create Date: 2019-10-29 13:50:36.173551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39430ae73fcf'
down_revision = 'bcad9f8f3ddb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assigned_office',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assigned_office')
    # ### end Alembic commands ###
