"""empty message

Revision ID: 7f834a5b3c7d
Revises: 
Create Date: 2019-11-18 11:15:01.829971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f834a5b3c7d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('earnings', sa.Column('sequence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('earnings', 'sequence')
    # ### end Alembic commands ###
