"""empty message

Revision ID: acf78300fe84
Revises: 7f834a5b3c7d
Create Date: 2019-11-28 16:40:09.187553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acf78300fe84'
down_revision = '7f834a5b3c7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('payroll_group_employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payroll_group_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payroll_group_id'], ['payroll_group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('earnings1')
    op.drop_constraint(None, 'payroll_earnings', type_='foreignkey')
    op.create_foreign_key(None, 'payroll_earnings', 'earnings', ['earnings_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'payroll_type_earnings', type_='foreignkey')
    op.create_foreign_key(None, 'payroll_type_earnings', 'earnings', ['earnings_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payroll_type_earnings', type_='foreignkey')
    op.create_foreign_key(None, 'payroll_type_earnings', 'earnings1', ['earnings_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'payroll_earnings', type_='foreignkey')
    op.create_foreign_key(None, 'payroll_earnings', 'earnings1', ['earnings_id'], ['id'], ondelete='CASCADE')
    op.create_table('earnings1',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('payment_type', sa.VARCHAR(length=3), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.Column('fixed_amount', sa.NUMERIC(precision=15, scale=2), nullable=True),
    sa.Column('formula', sa.VARCHAR(length=255), nullable=True),
    sa.Column('sequence', sa.FLOAT(), nullable=True),
    sa.CheckConstraint('active IN (0, 1)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('payroll_group_employee')
    op.drop_table('payroll_group')
    # ### end Alembic commands ###
